language: generic
sudo: required

services:
  - docker
 
before_install:
  - docker build -t santoshbs/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true santoshbs/docker-react npm run test    
